     
        stage('Build') {
            steps {
                // Clone the repository
                git url: 'https://github.com/OrangeMiracle/COMP367Lab2.git', branch: 'main'
                
                // Change to the Maven project directory
                dir('MavenWebApp/demo') {
                    // Build the Maven project
                    bat 'mvn clean install'
                }
            }
        }
